# Generated by Django 5.1.1 on 2024-10-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
