# Generated by Django 5.1.1 on 2024-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_credit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
