# Generated by Django 5.1.1 on 2024-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_credit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
